/*
 * generated by Xtext 2.37.0
 */
package org.example.qcm.dsl.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class QcmDslScopeProvider extends AbstractQcmDslScopeProvider {

}
