/*
 * generated by Xtext 2.37.0
 */
package org.example.qcm.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class QcmDslStandaloneSetup extends QcmDslStandaloneSetupGenerated {

	public static void doSetup() {
		new QcmDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
