/*
 * generated by Xtext 2.37.0
 */
package org.example.qcm.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QcmDslRuntimeModule extends AbstractQcmDslRuntimeModule {
}
