/*
 * generated by Xtext 2.37.0
 */
package org.example.qcm.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractQcmDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.example.qcm.dsl.qcmDsl.QcmDslPackage.eINSTANCE);
		return result;
	}
}
