/*
 * generated by Xtext 2.37.0
 */
package org.example.qcm.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.example.qcm.dsl.parser.antlr.internal.InternalQcmDslParser;
import org.example.qcm.dsl.services.QcmDslGrammarAccess;

public class QcmDslParser extends AbstractAntlrParser {

	@Inject
	private QcmDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalQcmDslParser createParser(XtextTokenStream stream) {
		return new InternalQcmDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Questionnaire";
	}

	public QcmDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QcmDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
