/**
 * generated by Xtext 2.37.0
 */
package org.example.qcm.dsl.qcmDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Proposition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.qcm.dsl.qcmDsl.Proposition#getTexte <em>Texte</em>}</li>
 *   <li>{@link org.example.qcm.dsl.qcmDsl.Proposition#getEstCorrecte <em>Est Correcte</em>}</li>
 * </ul>
 *
 * @see org.example.qcm.dsl.qcmDsl.QcmDslPackage#getProposition()
 * @model
 * @generated
 */
public interface Proposition extends EObject
{
  /**
   * Returns the value of the '<em><b>Texte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Texte</em>' attribute.
   * @see #setTexte(String)
   * @see org.example.qcm.dsl.qcmDsl.QcmDslPackage#getProposition_Texte()
   * @model
   * @generated
   */
  String getTexte();

  /**
   * Sets the value of the '{@link org.example.qcm.dsl.qcmDsl.Proposition#getTexte <em>Texte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Texte</em>' attribute.
   * @see #getTexte()
   * @generated
   */
  void setTexte(String value);

  /**
   * Returns the value of the '<em><b>Est Correcte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Est Correcte</em>' attribute.
   * @see #setEstCorrecte(String)
   * @see org.example.qcm.dsl.qcmDsl.QcmDslPackage#getProposition_EstCorrecte()
   * @model
   * @generated
   */
  String getEstCorrecte();

  /**
   * Sets the value of the '{@link org.example.qcm.dsl.qcmDsl.Proposition#getEstCorrecte <em>Est Correcte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Est Correcte</em>' attribute.
   * @see #getEstCorrecte()
   * @generated
   */
  void setEstCorrecte(String value);

} // Proposition
