/**
 * generated by Xtext 2.37.0
 */
package org.example.qcm.dsl.qcmDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Questionnaire</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.qcm.dsl.qcmDsl.Questionnaire#getName <em>Name</em>}</li>
 *   <li>{@link org.example.qcm.dsl.qcmDsl.Questionnaire#getMelange <em>Melange</em>}</li>
 *   <li>{@link org.example.qcm.dsl.qcmDsl.Questionnaire#getQuestions <em>Questions</em>}</li>
 * </ul>
 *
 * @see org.example.qcm.dsl.qcmDsl.QcmDslPackage#getQuestionnaire()
 * @model
 * @generated
 */
public interface Questionnaire extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.example.qcm.dsl.qcmDsl.QcmDslPackage#getQuestionnaire_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.example.qcm.dsl.qcmDsl.Questionnaire#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Melange</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Melange</em>' attribute.
   * @see #setMelange(String)
   * @see org.example.qcm.dsl.qcmDsl.QcmDslPackage#getQuestionnaire_Melange()
   * @model
   * @generated
   */
  String getMelange();

  /**
   * Sets the value of the '{@link org.example.qcm.dsl.qcmDsl.Questionnaire#getMelange <em>Melange</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Melange</em>' attribute.
   * @see #getMelange()
   * @generated
   */
  void setMelange(String value);

  /**
   * Returns the value of the '<em><b>Questions</b></em>' containment reference list.
   * The list contents are of type {@link org.example.qcm.dsl.qcmDsl.Question}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Questions</em>' containment reference list.
   * @see org.example.qcm.dsl.qcmDsl.QcmDslPackage#getQuestionnaire_Questions()
   * @model containment="true"
   * @generated
   */
  EList<Question> getQuestions();

} // Questionnaire
