/**
 * generated by Xtext 2.37.0
 */
package org.example.qcm.dsl.qcmDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.qcm.dsl.qcmDsl.Proposition;
import org.example.qcm.dsl.qcmDsl.QcmDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Proposition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.qcm.dsl.qcmDsl.impl.PropositionImpl#getTexte <em>Texte</em>}</li>
 *   <li>{@link org.example.qcm.dsl.qcmDsl.impl.PropositionImpl#getEstCorrecte <em>Est Correcte</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PropositionImpl extends MinimalEObjectImpl.Container implements Proposition
{
  /**
   * The default value of the '{@link #getTexte() <em>Texte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTexte()
   * @generated
   * @ordered
   */
  protected static final String TEXTE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTexte() <em>Texte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTexte()
   * @generated
   * @ordered
   */
  protected String texte = TEXTE_EDEFAULT;

  /**
   * The default value of the '{@link #getEstCorrecte() <em>Est Correcte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEstCorrecte()
   * @generated
   * @ordered
   */
  protected static final String EST_CORRECTE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEstCorrecte() <em>Est Correcte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEstCorrecte()
   * @generated
   * @ordered
   */
  protected String estCorrecte = EST_CORRECTE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PropositionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QcmDslPackage.Literals.PROPOSITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTexte()
  {
    return texte;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTexte(String newTexte)
  {
    String oldTexte = texte;
    texte = newTexte;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QcmDslPackage.PROPOSITION__TEXTE, oldTexte, texte));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEstCorrecte()
  {
    return estCorrecte;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEstCorrecte(String newEstCorrecte)
  {
    String oldEstCorrecte = estCorrecte;
    estCorrecte = newEstCorrecte;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QcmDslPackage.PROPOSITION__EST_CORRECTE, oldEstCorrecte, estCorrecte));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QcmDslPackage.PROPOSITION__TEXTE:
        return getTexte();
      case QcmDslPackage.PROPOSITION__EST_CORRECTE:
        return getEstCorrecte();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QcmDslPackage.PROPOSITION__TEXTE:
        setTexte((String)newValue);
        return;
      case QcmDslPackage.PROPOSITION__EST_CORRECTE:
        setEstCorrecte((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QcmDslPackage.PROPOSITION__TEXTE:
        setTexte(TEXTE_EDEFAULT);
        return;
      case QcmDslPackage.PROPOSITION__EST_CORRECTE:
        setEstCorrecte(EST_CORRECTE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QcmDslPackage.PROPOSITION__TEXTE:
        return TEXTE_EDEFAULT == null ? texte != null : !TEXTE_EDEFAULT.equals(texte);
      case QcmDslPackage.PROPOSITION__EST_CORRECTE:
        return EST_CORRECTE_EDEFAULT == null ? estCorrecte != null : !EST_CORRECTE_EDEFAULT.equals(estCorrecte);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (texte: ");
    result.append(texte);
    result.append(", estCorrecte: ");
    result.append(estCorrecte);
    result.append(')');
    return result.toString();
  }

} //PropositionImpl
