/**
 * generated by Xtext 2.37.0
 */
package org.example.qcm.dsl.qcmDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.example.qcm.dsl.qcmDsl.QcmDslPackage;
import org.example.qcm.dsl.qcmDsl.Question;
import org.example.qcm.dsl.qcmDsl.Questionnaire;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Questionnaire</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.qcm.dsl.qcmDsl.impl.QuestionnaireImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.example.qcm.dsl.qcmDsl.impl.QuestionnaireImpl#getMelange <em>Melange</em>}</li>
 *   <li>{@link org.example.qcm.dsl.qcmDsl.impl.QuestionnaireImpl#getQuestions <em>Questions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class QuestionnaireImpl extends MinimalEObjectImpl.Container implements Questionnaire
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getMelange() <em>Melange</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMelange()
   * @generated
   * @ordered
   */
  protected static final String MELANGE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMelange() <em>Melange</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMelange()
   * @generated
   * @ordered
   */
  protected String melange = MELANGE_EDEFAULT;

  /**
   * The cached value of the '{@link #getQuestions() <em>Questions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQuestions()
   * @generated
   * @ordered
   */
  protected EList<Question> questions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QuestionnaireImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QcmDslPackage.Literals.QUESTIONNAIRE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QcmDslPackage.QUESTIONNAIRE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMelange()
  {
    return melange;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMelange(String newMelange)
  {
    String oldMelange = melange;
    melange = newMelange;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QcmDslPackage.QUESTIONNAIRE__MELANGE, oldMelange, melange));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Question> getQuestions()
  {
    if (questions == null)
    {
      questions = new EObjectContainmentEList<Question>(Question.class, this, QcmDslPackage.QUESTIONNAIRE__QUESTIONS);
    }
    return questions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QcmDslPackage.QUESTIONNAIRE__QUESTIONS:
        return ((InternalEList<?>)getQuestions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QcmDslPackage.QUESTIONNAIRE__NAME:
        return getName();
      case QcmDslPackage.QUESTIONNAIRE__MELANGE:
        return getMelange();
      case QcmDslPackage.QUESTIONNAIRE__QUESTIONS:
        return getQuestions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QcmDslPackage.QUESTIONNAIRE__NAME:
        setName((String)newValue);
        return;
      case QcmDslPackage.QUESTIONNAIRE__MELANGE:
        setMelange((String)newValue);
        return;
      case QcmDslPackage.QUESTIONNAIRE__QUESTIONS:
        getQuestions().clear();
        getQuestions().addAll((Collection<? extends Question>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QcmDslPackage.QUESTIONNAIRE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case QcmDslPackage.QUESTIONNAIRE__MELANGE:
        setMelange(MELANGE_EDEFAULT);
        return;
      case QcmDslPackage.QUESTIONNAIRE__QUESTIONS:
        getQuestions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QcmDslPackage.QUESTIONNAIRE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case QcmDslPackage.QUESTIONNAIRE__MELANGE:
        return MELANGE_EDEFAULT == null ? melange != null : !MELANGE_EDEFAULT.equals(melange);
      case QcmDslPackage.QUESTIONNAIRE__QUESTIONS:
        return questions != null && !questions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", melange: ");
    result.append(melange);
    result.append(')');
    return result.toString();
  }

} //QuestionnaireImpl
