/*
 * generated by Xtext 2.37.0
 */
package org.example.qcm.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQcmDslScopeProvider extends DelegatingScopeProvider {
}
