<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="meta2" nsURI="http://www.example.org/meta2" nsPrefix="meta2">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PageQCM">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navRetour" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentationQuestion" lowerBound="1"
        upperBound="-1" eType="#//PresentationQuestion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationQuestion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="texteQuestion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difficulte" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estMelangee" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" lowerBound="1"
        upperBound="-1" eType="#//Option" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="etiquette" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="texteOption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estCorrecte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationQCM">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//typeNavigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResultatQCM">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scoreTotal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QCM">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estMelange" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageqcm" lowerBound="1"
        upperBound="-1" eType="#//PageQCM" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultat" lowerBound="1"
        upperBound="-1" eType="#//ResultatQCM" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="typeNavigation">
    <eLiterals name="SUIVANT"/>
    <eLiterals name="PRECEDENT" value="1"/>
  </eClassifiers>
</ecore:EPackage>